name: Nightly Build

permissions:
  contents: write
  actions: write

on:
  schedule:
    - cron: "0 14 * * *"  # 2PM UTC daily
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: nightly
  cancel-in-progress: true

jobs:
  check_recent_commit:
    runs-on: [self-hosted, windows]
    name: Check Recent Commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v3

      - id: should_run
        name: Check if latest commit date is within the previous 24 hours
        run: |
          if (git rev-list --since="24 hours ago" --all) {
            echo "should_run=true" >> $env:GITHUB_OUTPUT
          } else {
            echo "should_run=false" >> $env:GITHUB_OUTPUT
          }

  build_and_upload:
    runs-on: [self-hosted, windows]
    name: Build DLL
    needs: check_recent_commit
    if: needs.check_recent_commit.outputs.should_run == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Downgrade CMake to 3.29
        run: |
          Invoke-WebRequest -Uri https://github.com/Kitware/CMake/releases/download/v3.29.2/cmake-3.29.2-windows-x86_64.zip -OutFile cmake.zip
          Expand-Archive cmake.zip -DestinationPath cmake
          echo "${{ github.workspace }}/cmake/cmake-3.29.2-windows-x86_64/bin" | Out-File -Append -FilePath $env:GITHUB_PATH

      - name: Check CMake version
        run: cmake --version

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Generate CMake project
        run: cmake -D CMAKE_BUILD_TYPE=RelWithDebInfo -D OPTIMIZE=YES -S. -Bbuild -G Ninja

      - name: Build 64bit release DLL
        run: cmake --build ./build --config RelWithDebInfo --target ChronixV2 --

      - name: Manual Upload (Remove SSH/Upload part)
        run: |
            echo "Manual upload required. Please upload the DLL to the server."
        shell: powershell
